# Generated by Django 5.2.16 on 2026-07-14 21:18

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(help_text='Código do aparelho, ex: A102', max_length=20, unique=True)),
                ('localidade', models.CharField(max_length=120)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Informe o CPF apenas com 11 números (sem pontos ou traço).', regex='^\\d{11}$')])),
                ('cargo', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('localidade', models.CharField(blank=True, max_length=120)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='Informe o CPF apenas com 11 números (sem pontos ou traço).', regex='^\\d{11}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telefone', models.CharField(blank=True, max_length=20)),
                ('endereco', models.CharField(blank=True, max_length=200)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Dispositivo normalmente usado por este paciente', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pacientes', to='core.dispositivo')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='paciente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nome_completo'],
            },
        ),
        migrations.CreateModel(
            name='Leitura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
                ('medicao', models.DecimalField(decimal_places=2, help_text='Valor de PSA em ng/mL', max_digits=5)),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leituras', to='core.dispositivo')),
                ('funcionario', models.ForeignKey(blank=True, help_text='Quem realizou/registrou a leitura', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leituras', to='core.funcionario')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leituras', to='core.paciente')),
            ],
            options={
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('observacao', models.TextField(blank=True)),
                ('assinatura_nome', models.CharField(blank=True, help_text='Nome de quem assinou o relatório', max_length=150)),
                ('assinado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('funcionario_responsavel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='relatorios', to='core.funcionario')),
                ('leitura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='relatorio', to='core.leitura')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
