# Generated by Django 5.2.16 on 2026-07-17 21:08

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cor_r', models.PositiveSmallIntegerField(help_text='Componente vermelho da cor lida (0-255)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('cor_g', models.PositiveSmallIntegerField(help_text='Componente verde da cor lida (0-255)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('cor_b', models.PositiveSmallIntegerField(help_text='Componente azul da cor lida (0-255)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(255)])),
                ('nivel_risco', models.CharField(choices=[('baixo', 'Baixo'), ('moderado', 'Moderado'), ('alto', 'Alto')], max_length=10)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('leitura', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classificacao', to='core.leitura')),
            ],
            options={
                'ordering': ['-criado_em'],
            },
        ),
    ]
